added incoming fifo and outgoing fifo
sabaton-rs/dlt-daemon-rs pull request #5
Opened 2023-02-23 09:01 UTC by tsujjual

added incoming fifo and outgoing fifo

2023-02-23 09:02 UTC, tsujjual commented
need to add drop function to dltuserinner struct

2023-02-24 06:47 UTC, sjames requested changes

2023-02-24 06:47 UTC, sjames commented on dlt-user/src/lib.rs
> +            if let Ok(()) = fs::remove_file(self.user_path.as_ref().unwrap()) {};
unwrap here could cause a panic on drop. Avoid using unwrap here. Just ignore any errors.

2023-02-24 11:26 UTC, sjames approved these changes

2023-02-24 12:36 UTC, merged